version: '3'
services:
  mautic:
    image: mautic/mautic:${SOFTWARE_VERSION_TAG}
    container_name: mautic
    ports:
     - 172.17.0.1:9001:80
    volumes:
     - ./mautic:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=${DB_MYSQL_USER}
      - MAUTIC_DB_PASSWORD=${DB_MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${DB_MYSQL_NAME}
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - MAUTIC_CRON_HUBSPOT=
      - MAUTIC_CRON_SALESFORCE=
      - MAUTIC_CRON_PIPEDRIVE=
      - MAUTIC_CRON_ZOHO=
      - MAUTIC_CRON_SUGARCRM=
      - MAUTIC_CRON_DYNAMICS=
      - MAUTIC_TESTER=
      - MAUTIC_URL=https://${DOMAIN}
      - MAUTIC_ADMIN_EMAIL=${ADMIN_EMAIL}
      - MAUTIC_ADMIN_USERNAME=admin
      - MAUTIC_ADMIN_PASSWORD=${APP_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
    restart: always


  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: mautic-mysql
    restart: always
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_config/conf.d:/etc/mysql/conf.d
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
    