version: "3"

x-mautic-volumes: &mautic-volumes
  - ./mautic/config:/var/www/html/config:z
  - ./mautic/logs:/var/www/html/var/logs:z
  - ./mautic/media/files:/var/www/html/docroot/media/files:z
  - ./mautic/media/images:/var/www/html/docroot/media/images:z
  - ./cron:/opt/mautic/cron:z
  - mautic-docroot:/var/www/html/docroot:z

services:
  db:
    image: elestio/mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - mautic-docroot:/var/www/html/docroot:z
    depends_on:
      - mautic_web
    ports:
      - 172.17.0.1:7015:80

  mautic_web:
    image: mautic/mautic:${SOFTWARE_VERSION_TAG}
    restart: always
    links:
      - db:db
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_USER=${MYSQL_USER}
      - MAUTIC_DB_PASSWORD=${MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${MYSQL_DATABASE}
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - MAUTIC_URL=https://${CI_CD_DOMAIN}
      - MAUTIC_ADMIN_EMAIL=${ADMIN_EMAIL}
      - MAUTIC_ADMIN_USERNAME=admin
      - MAUTIC_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAUTIC_MESSENGER_DSN_EMAIL=doctrine://default
      - MAUTIC_MESSENGER_DSN_HIT=doctrine://default
    env_file:
      - .mautic_env
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy

  mautic_cron:
    image: mautic/mautic:${SOFTWARE_VERSION_TAG}
    restart: always
    links:
      - db:db
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    depends_on:
      mautic_web:
        condition: service_healthy

  mautic_worker:
    image: mautic/mautic:${SOFTWARE_VERSION_TAG}
    restart: always
    links:
      - db:db
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
      - MAUTIC_DB_HOST=db
      - MAUTIC_DB_USER=${MYSQL_USER}
      - MAUTIC_DB_PASSWORD=${MYSQL_PASSWORD}
      - MAUTIC_DB_NAME=${MYSQL_DATABASE}
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - MAUTIC_URL=https://${CI_CD_DOMAIN}
      - MAUTIC_ADMIN_EMAIL=${ADMIN_EMAIL}
      - MAUTIC_ADMIN_USERNAME=admin
      - MAUTIC_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MAUTIC_MESSENGER_DSN_EMAIL=doctrine://default
      - MAUTIC_MESSENGER_DSN_HIT=doctrine://default
    depends_on:
      mautic_web:
        condition: service_healthy

volumes:
  mautic-docroot:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mautic-docroot
      o: bind
